export const PRODUCTS = [
  "PICO", "CHOPPED TOM", "RED ENCH SAUCE", "GREEN ENCH SAUCE", "DARK RED ENCH SAUSE",
  "MILD (PESTO)", "BAJA SAUCE", "TARTER SAUCE", "LETTUCE", "CHEESE (SHREDDED)",
  "RANCHERO SAUCE", "PANCACKE MIX", "RED BEEF TAMALE", "GREEN CK TAMALE", "GREEN CORN TAMALE",
  "RED MENUDO", "WHITE MENUDO", "COCIDO", "ALBONDIGAS", "CARNE ASADA",
  "POLO ASADA", "PLAIN BEEF", "PLAIN CHICKEN", "GROUND BEEF", "CARNITAS",
  "BEANS", "RICE", "BEEF TACOS", "CK TACOS", "BEEF FLAUTAS",
  "CK FLAUTAS", "BEEF SUPER TACO", "CK SUPER TACO", "MACHACA BEEF", "MACHACA CK",
  "CHILLI RELLENOS", "FISH", "CEVICHE", "COOCKED SHRIMP", "OCTOPUS",
  "RED SALSA", "GREEN SALSA", "CHUNKY SALSA", "GUAC SALSA", "ORANGE SALSA",
  "BROWN SALSA", "GUACAMOLE", "GRAVY MIX", "RANCH", "PITAS",
  "ROLLED TACOS", "BEEF MINI CHIMI", "CK MINI CHIMI", "BEEF MINI TACO", "CK MINI TACO",
  "BEEF MINI FLAUTAS", "CK MINI FLAUTAS", "AL PASTOR", "BIRRIA"
];

export const BUCKET_SIZES = ["Small", "Medium", "Large"];
